[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=['@openzeppelin/=./lib/openzeppelin-contracts/', '@foundry-devops/src/=./lib/foundry-devops/src/']
ffi = true
fs_permissions = [{ access = "read", path = "./img/" }]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
